@echo off
echo Initializing Git...
git init
echo Setting branch to main...
git branch -M main
echo Configuring remote...
git remote add origin https://github.com/hm-damul/template-factory.git
git remote set-url origin https://github.com/hm-damul/template-factory.git
echo Adding files...
git add .
echo Committing...
git commit -m "Deploy for normal sales"
echo Pushing to GitHub (Force)...
git push origin main --force
echo Deployment process finished.
