# Secrets for Vercel Deployment
# This file is generated by the autonomous system.

NOWPAYMENTS_API_KEY = "ww-88314aa6-9392-40fd-a6d0-aefc8eb88523-widgetOnLoad"
NOWPAYMENTS_BASE_URL = "https://api.nowpayments.io"
